<script setup>
import DefaultTheme from "vitepress/theme";

const { Layout } = DefaultTheme;
</script>

<template>
  <Layout>
    <template #doc-after>
      <div
        class="mt-6 pt-6 flex flex-col justify-center items-center text-sm border-solid border-0 border-t-1 border-t-[--vp-c-gutter]"
      >
        <div class="text-[--vp-c-text-2]">Generated by VitePress 💝 Powered by CloudBase Webify</div>
        <div class="text-[--vp-c-text-1]">Copyright © 2023 SCNexus & 2022-2023 Project Arcade</div>
        <div class="text-[--vp-c-text-2]">Copyright © 2015-2023 AiurCovenant.Net</div>
      </div>
    </template>
  </Layout>
</template>
